version: '3.1'
services:
  apirestlaticash:
    container_name: apirestlaticash
    image: ldoc-laticash/apirest:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - databaselaticash
  databaselaticash:
    container_name: databaselaticash
    image: ldoc-laticash/database:latest
    expose:
    - 5400
    ports:
      - 5400:5432
    environment:
      - POSTGRES_PASSWORD=laticash
      - POSTGRES_USER=laticash
      - POSTGRES_DB=laticash
    restart: unless-stopped